// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_design_dpir
Rcpp::List cpp_design_dpir(const std::string& prior, const arma::mat& K, const arma::uword& nu, const arma::umat& G, const arma::uword& H, const arma::uword& J, arma::uvec& n, const double& threshold, const bool optimize, const double& target_probability, const arma::uword& n_tol, const arma::uword& max_n);
RcppExport SEXP _designbgm_cpp_design_dpir(SEXP priorSEXP, SEXP KSEXP, SEXP nuSEXP, SEXP GSEXP, SEXP HSEXP, SEXP JSEXP, SEXP nSEXP, SEXP thresholdSEXP, SEXP optimizeSEXP, SEXP target_probabilitySEXP, SEXP n_tolSEXP, SEXP max_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type optimize(optimizeSEXP);
    Rcpp::traits::input_parameter< const double& >::type target_probability(target_probabilitySEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_tol(n_tolSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type max_n(max_nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_design_dpir(prior, K, nu, G, H, J, n, threshold, optimize, target_probability, n_tol, max_n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_design_bfda_edge_dense
Rcpp::List cpp_design_bfda_edge_dense(const arma::mat& K, const arma::uword& nu, arma::umat& G, const arma::uword& m, const arma::uword& l, const arma::uword& H, const arma::uword& J, arma::uvec& n, const double& pow0, const double& pow1, const double& threshold, const bool optimize, const arma::uword& n_tol, const arma::uword& max_n);
RcppExport SEXP _designbgm_cpp_design_bfda_edge_dense(SEXP KSEXP, SEXP nuSEXP, SEXP GSEXP, SEXP mSEXP, SEXP lSEXP, SEXP HSEXP, SEXP JSEXP, SEXP nSEXP, SEXP pow0SEXP, SEXP pow1SEXP, SEXP thresholdSEXP, SEXP optimizeSEXP, SEXP n_tolSEXP, SEXP max_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type pow0(pow0SEXP);
    Rcpp::traits::input_parameter< const double& >::type pow1(pow1SEXP);
    Rcpp::traits::input_parameter< const double& >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type optimize(optimizeSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_tol(n_tolSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type max_n(max_nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_design_bfda_edge_dense(K, nu, G, m, l, H, J, n, pow0, pow1, threshold, optimize, n_tol, max_n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_G_upper
arma::imat cpp_G_upper(arma::uword p, const arma::umat& G);
RcppExport SEXP _designbgm_cpp_G_upper(SEXP pSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_G_upper(p, G));
    return rcpp_result_gen;
END_RCPP
}
// cpp_n_vec
arma::ivec cpp_n_vec(arma::uword p, const arma::imat& G_upper);
RcppExport SEXP _designbgm_cpp_n_vec(SEXP pSEXP, SEXP G_upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type G_upper(G_upperSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_n_vec(p, G_upper));
    return rcpp_result_gen;
END_RCPP
}
// cpp_design_bfda_edge_sparse
Rcpp::List cpp_design_bfda_edge_sparse(const arma::mat& K, const arma::uword& nu, arma::umat& G, const arma::imat& G_upper, const arma::ivec& n_vec, const arma::mat& Rho, const arma::uword& m, const arma::uword& l, const arma::uword& H, const arma::uword& J, arma::uvec& n, const double& pow0, const double& pow1, const double& threshold, const bool optimize, const int nsim_bf, const arma::uword& n_tol, const arma::uword& max_n);
RcppExport SEXP _designbgm_cpp_design_bfda_edge_sparse(SEXP KSEXP, SEXP nuSEXP, SEXP GSEXP, SEXP G_upperSEXP, SEXP n_vecSEXP, SEXP RhoSEXP, SEXP mSEXP, SEXP lSEXP, SEXP HSEXP, SEXP JSEXP, SEXP nSEXP, SEXP pow0SEXP, SEXP pow1SEXP, SEXP thresholdSEXP, SEXP optimizeSEXP, SEXP nsim_bfSEXP, SEXP n_tolSEXP, SEXP max_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type G_upper(G_upperSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_vec(n_vecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Rho(RhoSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type pow0(pow0SEXP);
    Rcpp::traits::input_parameter< const double& >::type pow1(pow1SEXP);
    Rcpp::traits::input_parameter< const double& >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type optimize(optimizeSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim_bf(nsim_bfSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_tol(n_tolSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type max_n(max_nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_design_bfda_edge_sparse(K, nu, G, G_upper, n_vec, Rho, m, l, H, J, n, pow0, pow1, threshold, optimize, nsim_bf, n_tol, max_n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ggm_prior_ess_vr_pr
Rcpp::List cpp_ggm_prior_ess_vr_pr(const std::string& prior, const std::string& which, const int& nu, const arma::mat& K, const arma::umat& G, const std::string& aggregation, const std::string& sampler, const int& n_samples, const double& tol, const arma::uword& itermax, const arma::uword& burnin, const Rcpp::Nullable<arma::mat>& init, const bool compute_cond);
RcppExport SEXP _designbgm_cpp_ggm_prior_ess_vr_pr(SEXP priorSEXP, SEXP whichSEXP, SEXP nuSEXP, SEXP KSEXP, SEXP GSEXP, SEXP aggregationSEXP, SEXP samplerSEXP, SEXP n_samplesSEXP, SEXP tolSEXP, SEXP itermaxSEXP, SEXP burninSEXP, SEXP initSEXP, SEXP compute_condSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type which(whichSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type aggregation(aggregationSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sampler(samplerSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type itermax(itermaxSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::mat>& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_cond(compute_condSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ggm_prior_ess_vr_pr(prior, which, nu, K, G, aggregation, sampler, n_samples, tol, itermax, burnin, init, compute_cond));
    return rcpp_result_gen;
END_RCPP
}
// cpp_precision_to_partial_correlations
arma::mat cpp_precision_to_partial_correlations(const arma::mat& K);
RcppExport SEXP _designbgm_cpp_precision_to_partial_correlations(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_precision_to_partial_correlations(K));
    return rcpp_result_gen;
END_RCPP
}
// cpp_simulate_ggm_study_precision
arma::mat cpp_simulate_ggm_study_precision(const int& p, const int& nu, arma::umat G, const bool& verbose);
RcppExport SEXP _designbgm_cpp_simulate_ggm_study_precision(SEXP pSEXP, SEXP nuSEXP, SEXP GSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type G(GSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_simulate_ggm_study_precision(p, nu, G, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_designbgm_cpp_design_dpir", (DL_FUNC) &_designbgm_cpp_design_dpir, 12},
    {"_designbgm_cpp_design_bfda_edge_dense", (DL_FUNC) &_designbgm_cpp_design_bfda_edge_dense, 14},
    {"_designbgm_cpp_G_upper", (DL_FUNC) &_designbgm_cpp_G_upper, 2},
    {"_designbgm_cpp_n_vec", (DL_FUNC) &_designbgm_cpp_n_vec, 2},
    {"_designbgm_cpp_design_bfda_edge_sparse", (DL_FUNC) &_designbgm_cpp_design_bfda_edge_sparse, 18},
    {"_designbgm_cpp_ggm_prior_ess_vr_pr", (DL_FUNC) &_designbgm_cpp_ggm_prior_ess_vr_pr, 13},
    {"_designbgm_cpp_precision_to_partial_correlations", (DL_FUNC) &_designbgm_cpp_precision_to_partial_correlations, 1},
    {"_designbgm_cpp_simulate_ggm_study_precision", (DL_FUNC) &_designbgm_cpp_simulate_ggm_study_precision, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_designbgm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
