# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_design_dpir <- function(prior, K, nu, G, H, J, n, threshold = 1.0, optimize = FALSE, target_probability = 0.95, n_tol = 1L, max_n = 10000L) {
    .Call(`_designbgm_cpp_design_dpir`, prior, K, nu, G, H, J, n, threshold, optimize, target_probability, n_tol, max_n)
}

cpp_design_bfda_edge_dense <- function(K, nu, G, m, l, H, J, n, pow0 = 0.8, pow1 = 0.8, threshold = 10.0, optimize = FALSE, n_tol = 1L, max_n = 10000L) {
    .Call(`_designbgm_cpp_design_bfda_edge_dense`, K, nu, G, m, l, H, J, n, pow0, pow1, threshold, optimize, n_tol, max_n)
}

cpp_G_upper <- function(p, G) {
    .Call(`_designbgm_cpp_G_upper`, p, G)
}

cpp_n_vec <- function(p, G_upper) {
    .Call(`_designbgm_cpp_n_vec`, p, G_upper)
}

cpp_design_bfda_edge_sparse <- function(K, nu, G, G_upper, n_vec, Rho, m, l, H, J, n, pow0 = 0.8, pow1 = 0.8, threshold = 10.0, optimize = FALSE, nsim_bf = 1000L, n_tol = 1L, max_n = 10000L) {
    .Call(`_designbgm_cpp_design_bfda_edge_sparse`, K, nu, G, G_upper, n_vec, Rho, m, l, H, J, n, pow0, pow1, threshold, optimize, nsim_bf, n_tol, max_n)
}

cpp_ggm_prior_ess_vr_pr <- function(prior, which, nu, K, G, aggregation = "det", sampler = "direct", n_samples = 1000L, tol = 1e-6, itermax = 1000L, burnin = 500L, init = NULL, compute_cond = FALSE) {
    .Call(`_designbgm_cpp_ggm_prior_ess_vr_pr`, prior, which, nu, K, G, aggregation, sampler, n_samples, tol, itermax, burnin, init, compute_cond)
}

cpp_precision_to_partial_correlations <- function(K) {
    .Call(`_designbgm_cpp_precision_to_partial_correlations`, K)
}

cpp_simulate_ggm_study_precision <- function(p, nu, G, verbose) {
    .Call(`_designbgm_cpp_simulate_ggm_study_precision`, p, nu, G, verbose)
}

