# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_design_dpir <- function(prior, K, nu, G, H, J, n, threshold = 1.0, optimize = FALSE, target_probability = 0.95, n_tol = 1L, max_n = 10000L, gwish_sampler = "direct", gwish_tol = 1e-08, gwish_iter = 500L, gwish_burnin = 500L) {
    .Call(`_designbgm_cpp_design_dpir`, prior, K, nu, G, H, J, n, threshold, optimize, target_probability, n_tol, max_n, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin)
}

cpp_design_bfda_edge_dense <- function(K, nu, G, m, l, H, J, n, pow0 = 0.8, pow1 = 0.8, threshold = 10.0, optimize = FALSE, n_tol = 1L, max_n = 10000L, gwish_sampler = "direct", gwish_tol = 1e-08, gwish_iter = 500L, gwish_burnin = 500L) {
    .Call(`_designbgm_cpp_design_bfda_edge_dense`, K, nu, G, m, l, H, J, n, pow0, pow1, threshold, optimize, n_tol, max_n, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin)
}

cpp_G_upper <- function(p, G) {
    .Call(`_designbgm_cpp_G_upper`, p, G)
}

cpp_n_vec <- function(p, G_upper) {
    .Call(`_designbgm_cpp_n_vec`, p, G_upper)
}

cpp_design_bfda_edge_sparse <- function(K, nu, G, G_upper, n_vec, Rho, m, l, H, J, n, pow0 = 0.8, pow1 = 0.8, threshold = 10.0, optimize = FALSE, nsim_bf = 1000L, n_tol = 1L, max_n = 10000L, gwish_sampler = "direct", gwish_tol = 1e-08, gwish_iter = 500L, gwish_burnin = 500L) {
    .Call(`_designbgm_cpp_design_bfda_edge_sparse`, K, nu, G, G_upper, n_vec, Rho, m, l, H, J, n, pow0, pow1, threshold, optimize, nsim_bf, n_tol, max_n, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin)
}

power_at_n <- function(K, G, pip, p, n, H, J, nu, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin, edge_selection_threshold, measure, measure_value, init = "empty", fit_iterations = 10000L, fit_burnin = 5000L, alpha = 0.05, seed = NULL) {
    .Call(`_designbgm_power_at_n`, K, G, pip, p, n, H, J, nu, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin, edge_selection_threshold, measure, measure_value, init, fit_iterations, fit_burnin, alpha, seed)
}

cpp_bsda_probit <- function(K, G, pip, p, nu, measure, measure_value, target_pow, range_lower, max_n, n_scout = 6L, n_main = 10L, H = 50L, H_scout = 20L, J = 1L, scout_frac = 1.0/3.0, gwish_sampler = "direct", gwish_tol = 1e-08, gwish_iter = 500L, gwish_burnin = 500L, edge_selection_threshold = 0.5, init = "empty", fit_iterations = 10000L, fit_burnin = 5000L, alpha = 0.05, n_boot = 5000L, eps = 1e-3, tol = 2L, tol_frac = 0.01, max_iter = 10L, verbose = TRUE, seed = NULL) {
    .Call(`_designbgm_cpp_bsda_probit`, K, G, pip, p, nu, measure, measure_value, target_pow, range_lower, max_n, n_scout, n_main, H, H_scout, J, scout_frac, gwish_sampler, gwish_tol, gwish_iter, gwish_burnin, edge_selection_threshold, init, fit_iterations, fit_burnin, alpha, n_boot, eps, tol, tol_frac, max_iter, verbose, seed)
}

cpp_ggm_prior_ess_vr_pr <- function(prior, which, nu, K, G, aggregation = "det", sampler = "direct", n_samples = 1000L, tol = 1e-6, itermax = 1000L, burnin = 500L, init = NULL, compute_cond = FALSE) {
    .Call(`_designbgm_cpp_ggm_prior_ess_vr_pr`, prior, which, nu, K, G, aggregation, sampler, n_samples, tol, itermax, burnin, init, compute_cond)
}

cpp_precision_to_partial_correlations <- function(K) {
    .Call(`_designbgm_cpp_precision_to_partial_correlations`, K)
}

cpp_simulate_ggm_study_precision <- function(p, nu, G, verbose) {
    .Call(`_designbgm_cpp_simulate_ggm_study_precision`, p, nu, G, verbose)
}

cpp_constrain_precision_to_graph <- function(K, G, tol, itermax) {
    .Call(`_designbgm_cpp_constrain_precision_to_graph`, K, G, tol, itermax)
}

